// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs godefs.go

package xeth

const (
	VlanVidMask	= 0xfff
	VlanNVid	= 0x1000

	MsgVersion	= 0x2

	IflaUnspec	= 0x0
	IflaXid		= 0x1
	IflaVid		= 0x2
	IflaKind	= 0x3

	DevKindUnspec	= 0x0
	DevKindPort	= 0x1
	DevKindVlan	= 0x2
	DevKindBridge	= 0x3
	DevKindLag	= 0x4

	MsgKindBreak		= 0x0
	MsgKindLinkStat		= 0x1
	MsgKindEthtoolStat	= 0x2
	MsgKindEthtoolFlags	= 0x3
	MsgKindEthtoolSettings	= 0x4
	MsgKindDumpIfInfo	= 0x5
	MsgKindCarrier		= 0x6
	MsgKindSpeed		= 0x7
	MsgKindIfInfo		= 0x8
	MsgKindIfa		= 0x9
	MsgKindDumpFibInfo	= 0xa
	MsgKindFibEntry		= 0xb
	MsgKindIfDel		= 0xc
	MsgKindNeighUpdate	= 0xd
	MsgKindIfVid		= 0xe
	MsgKindChangeUpperXid	= 0xf

	CarrierOff	= 0x0
	CarrierOn	= 0x1

	IfInfoReasonNew		= 0x0
	IfInfoReasonDel		= 0x1
	IfInfoReasonUp		= 0x2
	IfInfoReasonDown	= 0x3
	IfInfoReasonDump	= 0x4
	IfInfoReasonReg		= 0x5
	IfInfoReasonUnreg	= 0x6

	SizeofIfName			= 0x10
	SizeofEthAddr			= 0x6
	SizeofJumboFrame		= 0x2600
	SizeofMsg			= 0x10
	SizeofMsgBreak			= 0x10
	SizeofMsgCarrier		= 0x18
	SizeofMsgChangeUpperXid		= 0x20
	SizeofMsgDumpFibInfo		= 0x10
	SizeofMsgDumpIfInfo		= 0x10
	SizeofMsgEthtoolFlags		= 0x18
	SizeofMsgEthtoolSettings	= 0x38
	SizeofMsgIfa			= 0x20
	SizeofMsgIfInfo			= 0x40
	SizeofNextHop			= 0x18
	SizeofMsgFibEntry		= 0x28
	SizeofMsgNeighUpdate		= 0x38
	SizeofMsgSpeed			= 0x18
	SizeofMsgStat			= 0x20
)

type MsgHeader struct {
	Z64	uint64
	Z32	uint32
	Z16	uint16
	Version	uint8
	Kind	uint8
}

type MsgBreak struct {
	Header MsgHeader
}

type MsgCarrier struct {
	Header	MsgHeader
	Xid	uint32
	Flag	uint8
	Pad	[3]uint8
}

type MsgChangeUpperXid struct {
	Header	MsgHeader
	Upper	uint32
	Lower	uint32
	Linking	uint8
	Pad	[7]uint8
}

type MsgEthtoolFlags struct {
	Header	MsgHeader
	Xid	uint32
	Flags	uint32
}

type MsgEthtoolSettings struct {
	Header				MsgHeader
	Xid				uint32
	Speed				uint32
	Duplex				uint8
	Port				uint8
	Phy_address			uint8
	Autoneg				uint8
	Mdio_support			uint8
	Eth_tp_mdix			uint8
	Eth_tp_mdix_ctrl		uint8
	Link_mode_masks_nwords		uint8
	Link_modes_supported		[2]uint32
	Link_modes_advertising		[2]uint32
	Link_modes_lp_advertising	[2]uint32
}

type NextHop struct {
	Ifindex	int32
	Weight	int32
	Flags	uint32
	Gw	uint32
	Scope	uint8
	Pad	[7]uint8
}

type MsgFibentry struct {
	Header	MsgHeader
	Net	uint64
	Address	uint32
	Mask	uint32
	Event	uint8
	Nhs	uint8
	Tos	uint8
	Type	uint8
	Table	uint32
}

type MsgIfa struct {
	Header	MsgHeader
	Xid	uint32
	Event	uint32
	Address	uint32
	Mask	uint32
}

type MsgIfinfo struct {
	Header		MsgHeader
	Xid		uint32
	Reserved	uint32
	Ifname		[16]uint8
	Net		uint64
	Ifindex		int32
	Flags		uint32
	Addr		[6]uint8
	Kind		uint8
	Reason		uint8
}

type MsgNeighUpdate struct {
	Header		MsgHeader
	Net		uint64
	Ifindex		int32
	Family		uint8
	Len		uint8
	Reserved	uint16
	Dst		[16]uint8
	Lladdr		[6]uint8
	Pad		[2]uint8
}

type MsgSpeed struct {
	Header	MsgHeader
	Xid	uint32
	Mbps	uint32
}

type MsgStat struct {
	Header	MsgHeader
	Xid	uint32
	Index	uint32
	Count	uint64
}
